name: 1.0.$(Rev:r)

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: '**/Vonage.csproj'
  buildConfiguration: 'Release'
  versionByParam: 1.0.0.$(Build.BuildId)

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '$(project)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(project)'
    versioningScheme: 'byBuildNumber'
    buildProperties: 'Configuration=$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: nuget push
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    publishVstsFeed: '426e31b8-d721-476f-8e35-16e3a0669377'